/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface _SqlxMigrations {
  checksum: Buffer;
  description: string;
  execution_time: string;
  installed_on: Generated<string>;
  success: number;
  version: string | null;
}

export interface Playlists {
  created_at: Generated<string>;
  id: Generated<number>;
  name: string;
}

export interface DB {
  _sqlx_migrations: _SqlxMigrations;
  playlists: Playlists;
}
