/* eslint-disable perfectionist/sort-objects */

export const ID3_MAP = {
  TIT2: 'Title',
  TPE1: 'Artist',
  TALB: 'Album',
  TRCK: 'Track#',
  TYER: 'Year',
  TDRC: 'Recording date',
  TCON: 'Genre',
  APIC: 'Attached cover',
  COMM: 'Comments',
  TPE2: 'Album artist',
  TPOS: 'Disc#',
  TCOM: 'Composer',
  TBPM: 'BPM',
  TLEN: 'Length',
  USLT: 'Unsynchronized lyrics',
  SYLT: 'Synchronized lyrics',
  TXXX: 'User defined text',
  WXXX: 'User defined URL',
  TPUB: 'Publisher',
  TCOP: 'Copyright',
  TENC: 'Encoded by',
  TSSE: 'Encoding software',
  TFLT: 'File type',
  TKEY: 'Initial key',
  TLAN: 'Language',
  TMOO: 'Mood',
  TSRC: 'ISRC',
  WOAR: 'Artist URL',
  WOAF: 'Official file URL',
  WOAS: 'Official source URL',
  WCOP: 'Copyright URL',
  WPUB: 'Publisher URL',
  TPE3: 'Conductor',
  TPE4: 'Remixer',
  TEXT: 'Lyricist',
  TOLY: 'Original lyricist',
  TOPE: 'Original artist',
  TOAL: 'Original album',
  TOFN: 'Original filename',
  TORY: 'Original release year',
  TDOR: 'Original release date',
  TSOT: 'Title sort order',
  TSOP: 'Artist sort order',
  TSOA: 'Album sort order',
  TSO2: 'Album artist sort order',
  TSOC: 'Composer sort order',
  PRIV: 'Private frame',
  UFID: 'Unique file identifier',
  MCDI: 'Music CD identifier',
  PCNT: 'Play counter',
  POPM: 'Popularimeter',
  RBUF: 'Recommended buffer size',
  AENC: 'Audio encryption',
  ENCR: 'Encryption method registration',
  GRID: 'Group identification registration',
  SIGN: 'Signature frame',
  SEEK: 'Seek frame',
  ASPI: 'Audio seek point index',
  GEOB: 'General encapsulated object',
  LINK: 'Linked information',
  OWNE: 'Ownership frame',
  COMR: 'Commercial frame',
  USER: 'Terms of use',
  ETCO: 'Event timing codes',
  MLLT: 'MPEG location lookup table',
  SYTC: 'Synchronized tempo codes',
  RVRB: 'Reverb',
  EQU2: 'Equalization',
  RVA2: 'Relative volume adjustment',
  POSS: 'Position synchronization',
  TDAT: 'Date',
  TIME: 'Time',
  TRDA: 'Recording dates',
  TSIZ: 'Size',
  IPLS: 'Involved people',
  TIPL: 'Involved people list',
  TMCL: 'Musician credits list',
} as const

export type Id3FrameId = keyof typeof ID3_MAP
