// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type FileEntry = { path: string; name: string; tags: Partial<{ [key in string]: string }>; thumbnail_uri: string; full_uri: string }

const ARGS_MAP = { '':'{"get_waveform":["path","bin_size"],"play_track":["path"],"read_folder":["path"]}' }
export type Router = { "": {get_waveform: (path: string, binSize: number) => Promise<number[]>, 
play_track: (path: string) => Promise<null>, 
read_folder: (path: string) => Promise<FileEntry[]>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
