// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type FileEntry = { path: string; name: string; tags: SerializableTagItem[] }

export type SerializableTagItem = { key: string; value: string }

const ARGS_MAP = { '':'{"read_folder":["path"]}' }
export type Router = { "": {read_folder: (path: string) => Promise<FileEntry[]>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
